## 类和实例


In [1]:
class Animal(object):
    pass

In [2]:
class Animal(object):
    def __init__(self, name):
        self.name = name

In [3]:
animal = Animal('dog')
animal2 = Animal('dog2') 

In [4]:
print(animal2.name)

dog2


In [5]:
class Animal(object):
    def __init__(self, name):
        self.name1 = name
    def greet(self):
        print ('Hello, I am %s.' % self.name1)

In [6]:
dog1 = Animal('dog1')

In [7]:
dog1.name1

'dog1'

In [8]:
dog1.greet()

Hello, I am dog1.


### 访问限制

In [9]:
class Animal(object):
    def __init__(self, name):
        self.__name = name
    def greet(self):
        print ('Hello, I am %s.' % self.__name)

In [10]:
dog1 = Animal('dog1')

In [11]:
dog1.__name

AttributeError: 'Animal' object has no attribute '__name'

In [13]:
dog1.greet()

Hello, I am dog1.


### 继承

In [14]:
class Animal(object):
    def __init__(self, name):
        self.name = name
    def greet(self):
        print ('Hello, I am %s.' % self.name)

In [15]:
class Dog(object):
    def __init__(self, name):
        self.name = name
    def greet(self):
        print('WangWang.., I am %s.' % self.name)

In [16]:
dog2 = Dog('dog2')
#print(dog2.name)
dog2.greet()

WangWang.., I am dog2.


In [17]:
class Animal(object):
    def __init__(self, name):
        self.name = name
    def greet(self):
        print ('Hello, I am %s.' % self.name)
        
class Dog(Animal):
    def greet(self):
        print ('WangWang.., I am %s. ' % self.name)

In [18]:
dog3 = Dog('dog3')
# print(dog3.name)
dog3.greet()

WangWang.., I am dog3. 


In [19]:
class Dog(Animal):
    def greet(self):
        print ('WangWang.., I am %s. ' % self.name)
    def run(self):
        print ('I am running.I am running')

In [20]:
dog3 = Dog('dog3')
print(dog3.name)
dog3.greet()

dog3
WangWang.., I am dog3. 


In [21]:
dog3.run()

I am running.I am running


### super 用法

In [22]:
class Animal(object):
    def __init__(self, name):
        self.name = name
    def greet(self):
        print ('Hello, I am %s.' % self.name)

class Dog(Animal):
    def greet(self):
        super(Dog, self).greet()   
        print ('WangWang...')

In [23]:
dog = Dog('dog')

In [24]:
dog.greet()

Hello, I am dog.
WangWang...


In [25]:
class Base(object):
    def __init__(self, a, b):
        self.a = a
        self.b = b
    def show(self):
        print('(a,b) is (%d, %d)' % (self.a, self.b))

class A(Base):
    def __init__(self, a, b, c):
        super(A, self).__init__(a, b)  # Python3 可使用 super().__init__(a, b)
#         self.a = a
#         self.b = b
        self.c = c
    def show(self):
        print('(a,b,c) is (%d, %d, %d)' % (self.a, self.b, self.c))

In [26]:
x = Base(2,3)

In [27]:
x.show()

(a,b) is (2, 3)


In [28]:
y = A(1,3,4)
y.show()

(a,b,c) is (1, 3, 4)


In [29]:
import numpy as np

In [30]:
a = np.random.randn(4,4)

In [31]:
a

array([[-0.16931878, -2.06012569, -1.15814216, -0.81022491],
       [ 1.06366182, -0.54349478, -0.79881832, -1.98812023],
       [ 0.48305673,  0.47574833, -2.06680426, -0.32536512],
       [ 0.67527441,  0.50439391, -1.21915968,  0.12795908]])

In [35]:
b = a.reshape(2,2,2,2)

In [36]:
b

array([[[[-0.16931878, -2.06012569],
         [-1.15814216, -0.81022491]],

        [[ 1.06366182, -0.54349478],
         [-0.79881832, -1.98812023]]],


       [[[ 0.48305673,  0.47574833],
         [-2.06680426, -0.32536512]],

        [[ 0.67527441,  0.50439391],
         [-1.21915968,  0.12795908]]]])

In [37]:
c = b.transpose(0,2,1,3)

In [38]:
c

array([[[[-0.16931878, -2.06012569],
         [ 1.06366182, -0.54349478]],

        [[-1.15814216, -0.81022491],
         [-0.79881832, -1.98812023]]],


       [[[ 0.48305673,  0.47574833],
         [ 0.67527441,  0.50439391]],

        [[-2.06680426, -0.32536512],
         [-1.21915968,  0.12795908]]]])

In [39]:
d = c.reshape(4,2,2)

In [40]:
d[0]

array([[-0.16931878, -2.06012569],
       [ 1.06366182, -0.54349478]])

In [83]:
d[1]

array([[-1.15814216, -0.81022491],
       [-0.79881832, -1.98812023]])

In [43]:
a = np.random.rand(2,2)
print(a)

[[0.8744778  0.74333346]
 [0.43779935 0.6085417 ]]


In [85]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [86]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
a.shape

(3, 3)

In [88]:
a.squeeze().shape

(3, 3)

In [89]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
b = np.pad(a,(3,3),'symmetric') # 填充

In [91]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [92]:
b.shape

(9, 9)

In [93]:
b

array([[9, 8, 7, 7, 8, 9, 9, 8, 7],
       [6, 5, 4, 4, 5, 6, 6, 5, 4],
       [3, 2, 1, 1, 2, 3, 3, 2, 1],
       [3, 2, 1, 1, 2, 3, 3, 2, 1],
       [6, 5, 4, 4, 5, 6, 6, 5, 4],
       [9, 8, 7, 7, 8, 9, 9, 8, 7],
       [9, 8, 7, 7, 8, 9, 9, 8, 7],
       [6, 5, 4, 4, 5, 6, 6, 5, 4],
       [3, 2, 1, 1, 2, 3, 3, 2, 1]])

In [94]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [97]:
print(a)
np.random.randn(*a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


TypeError: only integer scalar arrays can be converted to a scalar index

In [98]:
a = np.expand_dims(a, 0) # 增加维度

In [99]:
a.shape

(1, 3, 3)

In [100]:
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [101]:
a = np.zeros((1,2,3))

In [102]:
np.random.randint(5)

3

In [103]:
import torch

In [104]:
a = torch.randn(3,1)

In [105]:
a

tensor([[-0.9878],
        [ 1.4253],
        [-0.8193]])

In [107]:
b = torch.randn(4,1)

In [108]:
b

tensor([[-0.3722],
        [ 0.7423],
        [-0.6940],
        [-1.5559]])

In [110]:
X = torch.randn(3,4,requires_grad=True) # 梯度

In [111]:
X

tensor([[ 1.4470,  0.4954, -0.0348, -0.6722],
        [-0.5150, -0.2877, -1.1240,  0.7700],
        [ 0.2447,  1.5459, -2.0045,  0.4998]], requires_grad=True)

In [112]:
y = torch.mm(torch.mm(a.transpose(1,0), X), b) # transpose转置

In [114]:
y

tensor([[-2.8832]], grad_fn=<MmBackward>)

In [116]:
y = torch.mm(torch.mm(a.t(), X), b)

In [117]:
y

tensor([[-2.8832]], grad_fn=<MmBackward>)

In [118]:
from torch import autograd
grads = autograd.grad(y, X) # y对X求导

In [119]:
print(grads)

(tensor([[ 0.3676, -0.7332,  0.6856,  1.5369],
        [-0.5305,  1.0580, -0.9892, -2.2177],
        [ 0.3049, -0.6082,  0.5686,  1.2748]]),)


In [120]:
print(torch.mm(a, b.t()))

tensor([[ 0.3676, -0.7332,  0.6856,  1.5369],
        [-0.5305,  1.0580, -0.9892, -2.2177],
        [ 0.3049, -0.6082,  0.5686,  1.2748]])


In [121]:
grads = autograd.grad(y, a)

RuntimeError: One of the differentiated Tensors does not require grad

In [122]:
print(a.requires_grad)

False


In [123]:
print(X.requires_grad)

True


In [124]:
a.dtype

torch.float32