In [1]:
import torch
print(torch.__version__)

1.6.0


### 自动求导机制

In [2]:
x = torch.randn(4,1, requires_grad=True)
y = torch.randn(4,1, requires_grad=True)
W = torch.randn(4,4)
print(x)
print(y)
print(W)

tensor([[-1.1177],
        [-1.1700],
        [-0.4650],
        [-0.2524]], requires_grad=True)
tensor([[ 0.1030],
        [-1.1759],
        [ 0.1910],
        [ 1.1102]], requires_grad=True)
tensor([[-2.1359, -0.4151,  0.1779,  0.6701],
        [-1.2360,  0.5365,  0.6934, -0.8714],
        [ 0.3592, -0.2674,  0.3616, -1.8989],
        [ 1.6630, -2.4166,  0.9667, -0.8981]])


In [3]:
z = torch.mm(torch.mm(torch.t(x), W),y)
print(z)

tensor([[0.9241]], grad_fn=<MmBackward>)


In [4]:
z = x.t().mm(W).mm(y).abs()
print(z)

tensor([[0.9241]], grad_fn=<AbsBackward>)


In [5]:
print(x.grad)

None


In [6]:
z.backward() # 调用backward()计算梯度

In [7]:
print(x.grad)

tensor([[ 1.0461],
        [-1.5932],
        [-1.6877],
        [ 2.2005]])


In [8]:
print(W.mm(y))

tensor([[ 1.0461],
        [-1.5932],
        [-1.6877],
        [ 2.2005]], grad_fn=<MmBackward>)


### 默认情况下，定义的tensor属性requires_grad为false

In [9]:
x = torch.randn(4,1)
print(x)
y = torch.mm(torch.t(x),x)
y.backward()

tensor([[-0.6705],
        [-0.2394],
        [ 0.2841],
        [-0.7306]])


RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [10]:
print(y)

print(x.grad)

print(2*x)

tensor([[1.1213]])
None
tensor([[-1.3409],
        [-0.4789],
        [ 0.5681],
        [-1.4612]])


### PyTorch Tensor 与 Numpy 转换

In [11]:
import numpy as np
import torch

a = np.random.randn(3,4)
print(a)
print(type(a))

[[-0.71310616  0.87578963  2.08235439  0.22503206]
 [ 0.02618542  0.62399363 -0.12654666  0.19626911]
 [-0.16733279  1.02441077  0.07931144  0.23200111]]
<class 'numpy.ndarray'>


In [12]:
a_tensor = torch.from_numpy(a) # numpy转tensor
print(a_tensor)
print(type(a_tensor))

tensor([[-0.7131,  0.8758,  2.0824,  0.2250],
        [ 0.0262,  0.6240, -0.1265,  0.1963],
        [-0.1673,  1.0244,  0.0793,  0.2320]], dtype=torch.float64)
<class 'torch.Tensor'>


In [13]:
b = a_tensor.numpy() # tensor转numpy
print(b)
print(type(b))

[[-0.71310616  0.87578963  2.08235439  0.22503206]
 [ 0.02618542  0.62399363 -0.12654666  0.19626911]
 [-0.16733279  1.02441077  0.07931144  0.23200111]]
<class 'numpy.ndarray'>


In [14]:
d_tensor = torch.randn(3, 4, requires_grad=False)
d_numpy = d_tensor.numpy()
print(d_numpy)
print(type(d_numpy))

[[ 0.5455371   0.3944307   1.557866   -0.05578891]
 [-1.6919385   0.46125388 -1.0978091  -0.6861558 ]
 [-0.6882169  -1.0346521   0.7827343  -0.96224   ]]
<class 'numpy.ndarray'>


In [15]:
d_tensor = torch.randn(3, 4, requires_grad=True)
d_numpy = d_tensor.numpy()
print(d_numpy)
print(type(d_numpy))

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [16]:
d_tensor = torch.randn(3, 4, requires_grad=True)
d_numpy = d_tensor.data.numpy()
print(d_numpy)
print(d_tensor.data)
print(type(d_numpy))

[[-1.8182073   2.3015518   0.55600864 -1.107132  ]
 [ 1.6612527   0.4081838  -0.24780194  2.5315604 ]
 [ 0.14758955  1.0971384  -0.8808657   0.21065423]]
tensor([[-1.8182,  2.3016,  0.5560, -1.1071],
        [ 1.6613,  0.4082, -0.2478,  2.5316],
        [ 0.1476,  1.0971, -0.8809,  0.2107]])
<class 'numpy.ndarray'>
