In [9]:
import torch

In [ ]:
x = torch.empty(5, 3)
print(x)
print(x.shape)

In [ ]:
x = torch.rand(5, 3)
print(x)

In [13]:
x = torch.randn(5, 3)
print(x)

tensor([[-0.2666,  0.1894, -0.2190],
        [ 2.0576, -0.0354,  0.0627],
        [-0.7663,  1.0993,  2.7565],
        [ 0.1753, -0.9315, -1.5055],
        [-0.6610,  1.3232,  0.0371]])


In [17]:
torch.manual_seed(0)
x = torch.randn(5, 3)
print(x)

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193],
        [-0.4033, -0.5966,  0.1820],
        [-0.8567,  1.1006, -1.0712]])


In [18]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [19]:
x = torch.randn(5,3)
y = torch.rand(5,3)
print(x + y)

tensor([[ 0.8489,  0.1348,  0.5769],
        [-0.2409, -0.7346,  0.8073],
        [ 1.9756,  1.5557,  1.5850],
        [ 1.1720,  1.3785, -0.9737],
        [-0.0946,  0.8934,  0.2166]])


In [20]:
print(torch.add(x, y))

tensor([[ 0.8489,  0.1348,  0.5769],
        [-0.2409, -0.7346,  0.8073],
        [ 1.9756,  1.5557,  1.5850],
        [ 1.1720,  1.3785, -0.9737],
        [-0.0946,  0.8934,  0.2166]])


In [21]:
print(y)
y.add_(x)
print(y)

tensor([[0.7262, 0.7011, 0.2038],
        [0.6511, 0.7745, 0.4369],
        [0.5191, 0.6159, 0.8102],
        [0.9801, 0.1147, 0.3168],
        [0.6965, 0.9143, 0.9351]])
tensor([[ 0.8489,  0.1348,  0.5769],
        [-0.2409, -0.7346,  0.8073],
        [ 1.9756,  1.5557,  1.5850],
        [ 1.1720,  1.3785, -0.9737],
        [-0.0946,  0.8934,  0.2166]])


In [22]:
y.zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [23]:
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [24]:
x = torch.randn(5,3)
print(x)

tensor([[-1.1938, -0.2233, -1.2706],
        [ 0.0193,  0.8868,  0.0552],
        [ 0.6880,  1.2326,  1.1580],
        [ 0.1673, -1.5773,  1.0689],
        [-0.5065, -1.4561,  2.2925]])


In [11]:
print(x[:, 1].shape)

torch.Size([5])


In [12]:
x[:, 1]

tensor([-1.6450,  0.5490,  0.9065,  2.6921, -0.2188])

In [13]:
print(x[:, 1].shape)

torch.Size([5, 1])


In [14]:
x[:, 1:2]

tensor([[-1.6450],
        [ 0.5490],
        [ 0.9065],
        [ 2.6921],
        [-0.2188]])

In [25]:
a = torch.ones(5)
print(a)
print(type(a))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>


In [26]:
b = a.numpy()
print(b)
print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [17]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [27]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [19]:
a = a * 2
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [20]:
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [21]:
a[1] = 2

In [22]:
print(a)

[1. 2. 1. 1. 1.]


In [23]:
print(b)

tensor([1., 2., 1., 1., 1.], dtype=torch.float64)


In [28]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

In [36]:
x = torch.randn(3,3)
y = torch.randn(3,3)
print(x)
print(y)

tensor([[ 0.5085, -0.0515, -0.6248],
        [ 0.2844, -0.9130,  1.1218],
        [-0.6852, -0.0445,  1.7928]])
tensor([[-0.8348,  0.8459,  0.1077],
        [ 0.4118, -2.1578, -0.1408],
        [ 0.0601, -2.5075,  2.1395]])


In [33]:
z = torch.mm(x,y)
print(z)

tensor([[ 1.9448,  2.0112,  1.1264],
        [ 1.4124,  1.0804,  1.0326],
        [-0.0806, -3.1318, -0.1550]])


In [34]:
x.mm(y)

tensor([[ 1.9448,  2.0112,  1.1264],
        [ 1.4124,  1.0804,  1.0326],
        [-0.0806, -3.1318, -0.1550]])

In [37]:
z = x*y
print(z)

tensor([[-0.4246, -0.0436, -0.0673],
        [ 0.1171,  1.9701, -0.1580],
        [-0.0412,  0.1116,  3.8358]])


In [29]:
b = z.zero_()
print(b)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [30]:
z

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [31]:
b[0,0] = 1

In [32]:
b

tensor([[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [33]:
z

tensor([[1., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [34]:
import torch
x = torch.tensor([5, 3])
y = torch.ones_like(x)
z = x.add(y)
print(z)


tensor([6, 4])


In [35]:
import torch
x = torch.tensor([5, 3])
y = torch.ones_like(x)
x.add_(y)
y.zero_()
print(x)
print(y)


tensor([6, 4])
tensor([0, 0])


In [ ]:
a = torch.ones(1,2)
b = a.numpy()
b[0][0] = 3
print('a =', a)
print('b =', b)


In [ ]:
import numpy as np
a = np.ones((1,3))
b = torch.from_numpy(a)
a[0][0] = 3
print('a =', a)
print('b =', b)


In [41]:
import numpy as np

x = np.ones((1,3))
print(x)
y = x
y[0][0] = 4
print(x)
print(y)


[[1. 1. 1.]]
[[4. 1. 1.]]
[[4. 1. 1.]]


In [39]:
id(x)

1367233792080

In [40]:
id(y)

1367233792080

In [42]:
import numpy as np

x = np.ones((1,3))
print(x)
y = x.copy()
y[0][0] = 4
print(x)
print(y)


[[1. 1. 1.]]
[[1. 1. 1.]]
[[4. 1. 1.]]


In [43]:
id(x)

1367234427840

In [44]:
id(y)

1367233808224

In [50]:
x = torch.tensor(1., requires_grad=True)
w = torch.tensor(2)
b = torch.tensor(3., requires_grad=True)

y = w*x + b

y.backward()

print(w.grad)
print(x.grad)
print(b.grad)


None
tensor(2.)
tensor(1.)


In [47]:
y = w*x + b
y.backward()

print(w.grad)
print(x.grad)
print(b.grad)


tensor(3.)
tensor(6.)
tensor(3.)


In [49]:
y = w*x + b
w.grad.zero_()
x.grad.zero_()
b.grad.zero_()

y.backward()
print(w.grad)
print(x.grad)
print(b.grad)


tensor(1.)
tensor(2.)
tensor(1.)
