In [1]:
import torch
print(torch.__version__)

ModuleNotFoundError: No module named 'torch'

In [2]:
x = torch.randn(4,1)

In [3]:
print(x)

tensor([[ 1.1229],
        [ 0.1073],
        [-1.6773],
        [-0.5879]])


In [4]:
print(x.requires_grad)

False


### 自动求导机制

In [5]:
x = torch.randn(4,1, requires_grad=True)
y = torch.randn(4,1, requires_grad=True)
W = torch.randn(4,4)
print(x)
print(y)
print(W)

tensor([[ 0.1431],
        [ 0.3217],
        [-0.9722],
        [-0.3150]], requires_grad=True)
tensor([[ 0.1384],
        [-1.3734],
        [-0.5565],
        [ 0.7581]], requires_grad=True)
tensor([[ 0.1174,  0.0862,  1.3644, -0.0503],
        [ 0.6206,  0.8085,  0.4048,  0.2743],
        [-0.5218,  0.4407, -0.6316,  0.0317],
        [-1.8617,  0.4754, -2.5823, -0.0730]])


In [ ]:
torch.trace(W.mm(y).t().mm(x))

In [ ]:
x.mm(W.mm(y).t())

In [ ]:
torch.trace(x.mm(W.mm(y).t()))

## $z = x^T W y $

In [6]:
z = torch.mm(torch.mm(torch.t(x), W),y)
print(z)

tensor([[-0.3186]], grad_fn=<MmBackward>)


In [7]:
z = x.t().mm(W).mm(y)
print(z)

tensor([[-0.3186]], grad_fn=<MmBackward>)


In [8]:
print(x.grad)

None


In [9]:
print(y.grad)

None


In [10]:
z.backward()

In [11]:
print(x.grad)

tensor([[-0.8995],
        [-1.0417],
        [-0.3020],
        [ 0.4710]])


In [12]:
print(W.mm(y))

tensor([[-0.8995],
        [-1.0417],
        [-0.3020],
        [ 0.4710]], grad_fn=<MmBackward>)


In [13]:
print(y.grad)

tensor([[ 1.3102],
        [-0.3058],
        [ 1.7528],
        [ 0.0732]])


In [14]:
print(W.t().mm(x))

tensor([[ 1.3102],
        [-0.3058],
        [ 1.7528],
        [ 0.0732]], grad_fn=<MmBackward>)


In [15]:
x.grad.zero_()

tensor([[0.],
        [0.],
        [0.],
        [0.]])

In [16]:
y.grad.zero_()

tensor([[0.],
        [0.],
        [0.],
        [0.]])

In [17]:
print(x.grad)

tensor([[0.],
        [0.],
        [0.],
        [0.]])


### 默认情况下，定义的tensor属性requires_grad为false

In [19]:
x = torch.randn(4,1, requires_grad=True)
print(x)
y = torch.mm(torch.t(x),x)
print(y)
y.backward()

tensor([[ 1.2129],
        [-0.6779],
        [ 1.8371],
        [-0.1568]], requires_grad=True)
tensor([[5.3301]], grad_fn=<MmBackward>)


In [20]:
print(x.grad)

tensor([[ 2.4259],
        [-1.3558],
        [ 3.6741],
        [-0.3135]])


In [21]:
print(y)

print(x.grad)

print(2*x)

tensor([[5.3301]], grad_fn=<MmBackward>)
tensor([[ 2.4259],
        [-1.3558],
        [ 3.6741],
        [-0.3135]])
tensor([[ 2.4259],
        [-1.3558],
        [ 3.6741],
        [-0.3135]], grad_fn=<MulBackward0>)


# 给定数据

In [23]:
import torch
torch.manual_seed(0)

x = torch.randn(10,4)
W = torch.randn(4,4, requires_grad=True)
y = torch.randn(10,4)

# print(x)
# print(y)
print(W)

tensor([[ 0.2055, -0.4503, -0.5731, -0.5554],
        [ 0.5943,  1.5419,  0.5073, -0.5910],
        [-1.3253,  0.1886, -0.0691, -0.4949],
        [-1.4959, -0.1938,  0.4455,  1.3253]], requires_grad=True)


# 目标函数 $f = ||max(XW,0)-Y||^2_F $

# $f = ||\hat{Y}-Y||^2_F $; $\hat{Y} = max(Z,0)$; $Z = XW$

In [ ]:
# f = (torch.clamp(x.mm(W), 0) - y).pow(2).sum()

In [24]:
z = x.mm(W)

In [27]:
f = (y_hat - y).pow(2).sum()

In [28]:
print(f)

tensor(99.9048, grad_fn=<SumBackward0>)


In [29]:
# W.grad.zero_()
print(W.grad)


None


In [30]:
f.backward()

## 直接求导

In [31]:
print(W.grad)

tensor([[ 18.2980,   2.7573,   2.3914,  -0.1974],
        [ 11.0817,   6.6428,   2.5163, -20.3225],
        [ -8.6662,   3.4506,  -1.8979,  -3.3608],
        [-21.1681,  -6.6739,  -1.0693,  27.0278]])


## 公式推导求导

In [32]:
y_hat_grad = 
# print(y_hat_grad)

In [33]:
z_grad = 

# print(z_grad)

In [34]:
W_grad = 

tensor([[ 18.2980,   2.7573,   2.3914,  -0.1974],
        [ 11.0817,   6.6428,   2.5163, -20.3225],
        [ -8.6662,   3.4506,  -1.8979,  -3.3608],
        [-21.1681,  -6.6739,  -1.0693,  27.0278]], grad_fn=<MmBackward>)


### PyTorch Tensor 与 Numpy 转换

In [ ]:
import numpy as np
import torch

a = np.random.randn(3,4)
print(a)
print(type(a))

In [ ]:
a_tensor = torch.from_numpy(a)
print(a_tensor)
print(type(a_tensor))

In [ ]:
b = a_tensor.numpy()
print(b)
print(type(b))

In [ ]:
d_tensor = torch.randn(3, 4, requires_grad=False)
d_numpy = d_tensor.numpy()
print(d_numpy)
print(type(d_numpy))

In [ ]:
d_tensor = torch.randn(3, 4, requires_grad=True)
d_numpy = d_tensor.numpy()
print(d_numpy)
print(type(d_numpy))

In [ ]:
d_tensor = torch.randn(3, 4, requires_grad=True)
d_numpy = d_tensor.data.numpy()
print(d_numpy)
print(d_tensor.data)
print(type(d_numpy))